schema:
  file: ./schema.graphql

dataSources:
  - kind: ethereum
    name: Ethereum-Event
    network: https://data-seed-prebsc-1-s1.binance.org:8545/
    mapping:
      language: rust
      handlers:
        - handler: handleEvent
          kind: ethereum/EventHandler

