description: Log Messages for Solana
repository: https://github.com/massbitprotocol/massbitprotocol/tree/main/user-example
schema:
  file: ./schema.graphql
dataSources:
  - kind: solana
    name: Solana-Log-Messages
    network: mainnet
    source:
      address: '0xf73D010412Fb5835C310728F0Ba1b7DFDe88379A'
      abi: SolanaLogMessages
    mapping:
      kind: solana/LogMessagesHandler
      apiVersion: 0.0.4
      language: rust
      entities:
        - SolanaLogMessages
      blockHandlers:
        - handler: handleLogMessages
      file: ./src/mapping.rs
      abis:
        - name: SolanaLogMessages
          file: ./abis/SolanaLogMessages.json