[workspace]
members = [
    "analytics",
    "chain-reader/chain-reader",
    "core/chain/substrate",
    "core/chain/solana",
    "core/chain/ethereum",
    "core/drive",
    "core/index-store",
    "cli",
    "utils",
    "chain/ethereum",
    "massbit",
    "runtime/wasm",
    "runtime/derive",
    "store/postgres",
    "manager",
]
exclude = ["code-compiler/generated"]

[patch.crates-io]
# Include protection against stack overflow when parsing from this PR: https://github.com/graphql-rust/graphql-parser/commit/45167b53e9533c331298683577ba8df7e43480ac
graphql-parser = {git="https://github.com/graphql-rust/graphql-parser", rev="45167b53e9533c331298683577ba8df7e43480ac"}

