[workspace]
members = [
    "chain-reader/chain-reader",
    "indexer/main",
    "mock",
    "core/chain/substrate",
    "indexer/main",
    "plugin/plugin",
    "plugin/test-plugin"
]
exclude = ["code-compiler/generated"]
