[store]
[store.primary]
connection = "postgresql://postgres:postgres@localhost:5432/massbit"
pool_size = 10

[chains.harmony]
provider = [
    { label = "harmony-0", url = "https://polygon-rpc.com", features = [] },
    { label = "firehose", details = { type = "firehose", url = "http://localhost:50051" } } # Chain reader
]