[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@localhost:5432/graph-node"
pool_size = 10

[chains.mainnet]
provider = [
    { label = "harmony-0", url = "https://a.api.s0.t.hmny.io/", features = [] },
#    { label = "firehose", details = { type = "firehose", url = "http://localhost:50051" } } # Chain reader
]

[chains.matic]
provider = [
    { label = "matic-0", url = "https://polygon-rpc.com", features = [] },
    #    { label = "firehose", details = { type = "firehose", url = "http://localhost:50051" } } # Chain reader
]