specVersion: 0.0.2
description: Block for Solana
repository: https://github.com/massbitprotocol/massbitprotocol/tree/main/user-example
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: Ethereum-Block
    network: mainnet
    source:
      address: '0xf73D010412Fb5835C310728F0Ba1b7DFDe88379A'
      abi: EthereumBlock
    mapping:
      kind: ethereum/BlockHandler
      apiVersion: 0.0.4
      language: rust
      entities:
        - EthereumBlock
      blockHandlers:
        - handler: handleBlock
      file: ./src/mapping.rs
      abis:
        - name: EthereumBlock
          file: ./abis/EthereumBlock.json