schema:
  file: ./schema.graphql

dataSources:
  - kind: ethereum
    name: Ethereum-Block
    network: https://data-seed-prebsc-1-s1.binance.org:8545/
    mapping:
      language: rust
      handlers:
        - handler: handleBlock
          kind: ethereum/BlockHandler

