[package]
name = "massbit-chain-ethereum"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { version = "1.0", optional = false }
serde = "1.0.126"
log = "0.4.14"
env_logger = "0.9.0"
bs58 = "0.4.0"
futures = "0.1.31"
tokio-compat-02 = "0.2"
############# Ethereum
# master contains changes such as
# https://github.com/paritytech/ethabi/pull/140, which upstream does not want
# and we should try to implement on top of ethabi instead of inside it, and
# tuple support which isn't upstreamed yet. For now, we shall deviate from
# ethabi, but long term we want to find a way to drop our fork.
ethabi = { git = "https://github.com/graphprotocol/ethabi.git", branch = "master" }
stable-hash = { git = "https://github.com/graphprotocol/stable-hash" }
anyhow = "1.0"
hex = "0.4.3"
tiny-keccak = "1.5.0"
futures03 = { version = "0.3.1", package = "futures", features = ["compat"] }
utils = { path = "../../../utils" }
massbit = { path = "../../../massbit" }
[dependencies.web3]
package = "web3"
git = "https://github.com/graphprotocol/rust-web3"
branch = "master"

[dependencies.graph]
package = "graph"
git = "https://github.com/massbitprotocol/massbit-graph-node"
branch = "main"

[dependencies.graph-chain-ethereum]
package = "graph-chain-ethereum"
git = "https://github.com/massbitprotocol/massbit-graph-node"
branch = "main"

[dependencies.graph-runtime-wasm]
package = "graph-runtime-wasm"
git = "https://github.com/massbitprotocol/massbit-graph-node"
branch = "main"