specVersion: 0.0.2
description: Extrinsic for Substrate Node
repository: https://github.com/massbitprotocol/massbitprotocol/tree/main/user-example
schema:
  file: ./schema.graphql
dataSources:
  - kind: substrate
    name: substrate-extrinsic
    network: mainnet
    source:
      address: '0xf73D010412Fb5835C310728F0Ba1b7DFDe88379A'
      abi: SubstrateExtrinsic
    mapping:
      kind: substrate/ExtrinsicHandler
      apiVersion: 0.0.4
      language: rust
      entities:
        - SubstrateExtrinsic
      blockHandlers:
        - handler: handleExtrinsic
      file: ./src/mapping.rs
      abis:
        - name: SubstrateExtrinsic
          file: ./abis/SubstrateExtrinsic.json