[package]
name = "massbit-storage-postgres"
version = "0.1.0"
edition = "2018"


[dependencies]
derive_more = { version = "0.99.14" }
diesel = { version = "1.4.7", features = ["postgres", "serde_json", "numeric", "r2d2"] }
diesel-dynamic-schema = { git = "https://github.com/diesel-rs/diesel-dynamic-schema", rev="a8ec4fb1" }
diesel-derive-enum = { version = "1.1", features = ["postgres"] }
diesel_migrations = "1.3.0"
diesel_derives = "1.4.1"
lru_time_cache = "0.11"
postgres = "0.19.1"
graphql-parser = "0.4.0"
Inflector = "0.11.4"
itertools = "0.10.3"
rand = "0.8"
maybe-owned = "0.3.4"
hex = "0.4.3"
backtrace = "0.3"
serde_derive        = { version = "1.0", optional = false }
massbit-common = { path = "../../common" }
indexer-orm = { path = "../../orm" }
massbit-data = { path= "../../data" }
massbit-solana-sdk = { path = "../../../chain/solana-sdk" }