specVersion: 0.0.2
description: Block for Substrate Node
repository: https://github.com/massbitprotocol/massbitprotocol/tree/main/user-example
schema:
  file: ./schema.graphql
dataSources:
  - kind: substrate
    name: substrate-block
    network: mainnet
    source:
      address: '0xf73D010412Fb5835C310728F0Ba1b7DFDe88379A'
      abi: SubstrateBlock
    mapping:
      kind: substrate/BlockHandler
      apiVersion: 0.0.4
      language: rust
      entities:
        - SubstrateBlock
      blockHandlers:
        - handler: handleBlock
      file: ./src/mapping.rs
      abis:
        - name: SubstrateBlock
          file: ./abis/SubstrateBlock.json