[package]
name = "block"
version = "0.1.0"
authors = ["lap50561"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.0", features = ["postgres"] }

# Massbit Dependencies
massbit-chain-substrate = { path = "../../core/chain/substrate"}
plugin = { path = "../../plugin"}
index-store = { path = "../../core/index-store"}

[lib]
crate-type = ["cdylib"]